<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project default="build_jar" name="Create all Jars for Project DbExport">
	<property name="antbuildhelp.version" value="26.0.2" />

	<property name="commons-collections4.version" value="4.4" />
	<property name="commons-compress.version" value="1.24.0" />
	<property name="commons-io.version" value="2.14.0" />
	<property name="commons-math3.version" value="3.6.1" />
	<property name="jna.version" value="5.13.0" />
	<property name="log4j.version" value="2.20.0" />
	<property name="poi.version" value="5.2.4" />
	<property name="xmlbeans.version" value="5.1.1" />
	<property name="zip4j.version" value="2.11.5" />
	<property name="kdbx.version" value="26.1.1" />
	<property name="csv.version" value="26.1.2" />
	<property name="json.version" value="26.2.3" />
	<property name="vcf.version" value="26.1.1" />
	<property name="proxyautoconfig.version" value="26.1.1" />
	<property name="network.version" value="26.0.31" />
	<property name="dbutilities.version" value="26.1.2" />
	<property name="soderer-utilities.version" value="26.2.53" />
	<property name="hamcrest.version" value="2.2" />
	<property name="junit.version" value="4.13.2" />

	<property name="mariadb-java-client.version" value="3.5.9" />
	<property name="mysql-connector-j.version" value="9.7.0" />
	<property name="hsqldb.version" value="2.7.4" />
	<property name="mssql-jdbc.version" value="13.4.0.jre11" />
	<property name="postgresql.version" value="42.7.13" />
	<property name="sqlite-jdbc.version" value="3.53.2.1" />
	<property name="ojdbc11.version" value="23.26.3.0.0" />
	<property name="orai18n.version" value="23.26.3.0.0" />
	<property name="derby.version" value="10.17.1.0" />

	<target name="build_jar" depends="build_setup, cleanup_before, create_jar, sign_jar, cleanup_after" />

	<target name="probe-proxy">
		<condition property="proxy.enabled">
			<and>
				<isset property="proxy.host" />
				<isreachable host="${proxy.host}" />
			</and>
		</condition>
	</target>

	<target name="proxy" depends="probe-proxy" if="proxy.enabled">
		<property name="proxy.port" value="80" />
		<property name="proxy.user" value="" />
		<property name="proxy.pass" value="" />
		<setproxy proxyhost="${proxy.host}" proxyport="${proxy.port}" proxyuser="${proxy.user}" proxypassword="${proxy.pass}" />
	</target>

	<available file="lib_build/antbuildhelp-${antbuildhelp.version}.jar" property="antbuildhelp.available" />
	<target name="get_antbuildhelp" unless="antbuildhelp.available">
		<mkdir dir="lib_build/" />
		<delete>
			<fileset dir="lib_build" includes="antbuildhelp-*.jar" />
		</delete>
		<get src="https://github.com/hudeany/antbuildhelp/releases/download/${antbuildhelp.version}/antbuildhelp-${antbuildhelp.version}.jar" dest="lib_build/" />
	</target>

	<!-- typedef must run on every build (Ant doesn't remember task registrations between runs),
	     so it lives in its own target with no "unless" - not inside get_antbuildhelp, which is
	     skipped whenever the jar is already cached from a previous run. -->
	<target name="register_antbuildhelp" depends="get_antbuildhelp">
		<typedef resource="de/soderer/antbuildhelp/antlib.xml" classpath="lib_build/antbuildhelp-${antbuildhelp.version}.jar" />
	</target>

	<target name="build_setup" depends="register_antbuildhelp">
		<loadfile property="build.version" srcFile="build.version" failonerror="false" />
		<property name="build.version" value="25.0.0" />
		<echo message="build.version: ${build.version}" />

		<property file="${user.home}/git/codeSigning.properties" />

		<tstamp>
			<format property="buildTime" pattern="yyyy-MM-dd HH:mm:ss" locale="en" />
		</tstamp>
		<echo message="buildTime: ${buildTime}" />

		<property name="buildPath" value="build" />
		<echo message="buildPath: ${buildPath}" />
	</target>

	<target name="cleanup_before">
		<delete dir="${buildPath}" />
		<mkdir dir="${buildPath}" />

		<delete dir="${buildPath}/bin" />
		<mkdir dir="${buildPath}/bin" />
	</target>

	<target name="download_dependencies" depends="proxy">
		<getDependency url="https://repo1.maven.org/maven2" groupId="org.apache.commons" artifactId="commons-collections4" version="${commons-collections4.version}" />
		<getDependency url="https://repo1.maven.org/maven2" groupId="org.apache.commons" artifactId="commons-compress" version="${commons-compress.version}" />
		<getDependency url="https://repo1.maven.org/maven2" groupId="commons-io" artifactId="commons-io" version="${commons-io.version}" />
		<getDependency url="https://repo1.maven.org/maven2" groupId="org.apache.commons" artifactId="commons-math3" version="${commons-math3.version}" />
		<getDependency url="https://repo1.maven.org/maven2" groupId="net.java.dev.jna" artifactId="jna" version="${jna.version}" />
		<getDependency url="https://repo1.maven.org/maven2" groupId="org.apache.logging.log4j" artifactId="log4j-1.2-api" version="${log4j.version}" />
		<getDependency url="https://repo1.maven.org/maven2" groupId="org.apache.logging.log4j" artifactId="log4j-api" version="${log4j.version}" />
		<getDependency url="https://repo1.maven.org/maven2" groupId="org.apache.logging.log4j" artifactId="log4j-core" version="${log4j.version}" />
		<getDependency url="https://repo1.maven.org/maven2" groupId="org.apache.poi" artifactId="poi" version="${poi.version}" />
		<getDependency url="https://repo1.maven.org/maven2" groupId="org.apache.poi" artifactId="poi-ooxml" version="${poi.version}" />
		<getDependency url="https://repo1.maven.org/maven2" groupId="org.apache.poi" artifactId="poi-ooxml-full" version="${poi.version}" />
		<getDependency url="https://repo1.maven.org/maven2" groupId="org.apache.xmlbeans" artifactId="xmlbeans" version="${xmlbeans.version}" />
		<getDependency url="https://repo1.maven.org/maven2" groupId="net.lingala.zip4j" artifactId="zip4j" version="${zip4j.version}" />

		<getDependency name="kdbx" version="${kdbx.version}" url="https://github.com/hudeany/kdbx/releases/download/{version}/kdbx-{version}.jar" />
		<getDependency name="csv" version="${csv.version}" url="https://github.com/hudeany/csv/releases/download/{version}/csv-{version}.jar" />
		<getDependency name="json" version="${json.version}" url="https://github.com/hudeany/json/releases/download/{version}/json-{version}.jar" />
		<getDependency name="vcf" version="${vcf.version}" url="https://github.com/hudeany/vcf/releases/download/{version}/vcf-{version}.jar" />
		<getDependency name="proxyautoconfig" version="${proxyautoconfig.version}" url="https://github.com/hudeany/ProxyAutoConfig/releases/download/{version}/proxyautoconfig-{version}.jar" />
		<getDependency name="network" version="${network.version}" url="https://github.com/hudeany/network/releases/download/{version}/network-{version}.jar" />
		<getDependency name="dbutilities" version="${dbutilities.version}" url="https://github.com/hudeany/DbUtilities/releases/download/{version}/dbutilities-{version}.jar" />

		<getDependency url="https://soderer.de/maven2" groupId="de.soderer" artifactId="soderer-utilities" version="${soderer-utilities.version}" />
		<getDependency url="https://soderer.de/maven2" groupId="de.soderer" artifactId="soderer-utilities" version="${soderer-utilities.version}" classifier="sources" />

		<getDependency libDir="lib_test" url="https://repo1.maven.org/maven2" groupId="org.hamcrest" artifactId="hamcrest" version="${hamcrest.version}" />
		<getDependency libDir="lib_test" url="https://repo1.maven.org/maven2" groupId="org.hamcrest" artifactId="hamcrest-core" version="${hamcrest.version}" />
		<getDependency libDir="lib_test" url="https://repo1.maven.org/maven2" groupId="junit" artifactId="junit" version="${junit.version}" />
	</target>

	<target name="download_dbconnectors" depends="proxy">
		<getDependency libDir="lib_db" url="https://repo1.maven.org/maven2" groupId="org.mariadb.jdbc" artifactId="mariadb-java-client" version="${mariadb-java-client.version}" />
		<getDependency libDir="lib_db" url="https://repo1.maven.org/maven2" groupId="com.mysql" artifactId="mysql-connector-j" version="${mysql-connector-j.version}" />
		<getDependency libDir="lib_db" url="https://repo1.maven.org/maven2" groupId="org.hsqldb" artifactId="hsqldb" version="${hsqldb.version}" />
		<getDependency libDir="lib_db" url="https://repo1.maven.org/maven2" groupId="com.microsoft.sqlserver" artifactId="mssql-jdbc" version="${mssql-jdbc.version}" />
		<getDependency libDir="lib_db" url="https://repo1.maven.org/maven2" groupId="org.postgresql" artifactId="postgresql" version="${postgresql.version}" />
		<getDependency libDir="lib_db" url="https://repo1.maven.org/maven2" groupId="org.xerial" artifactId="sqlite-jdbc" version="${sqlite-jdbc.version}" />
		<getDependency libDir="lib_db" url="https://repo1.maven.org/maven2" groupId="com.oracle.database.jdbc" artifactId="ojdbc11" version="${ojdbc11.version}" />
		<getDependency libDir="lib_db" url="https://repo1.maven.org/maven2" groupId="com.oracle.database.nls" artifactId="orai18n" version="${orai18n.version}" />
		<getDependency libDir="lib_db" url="https://repo1.maven.org/maven2" groupId="org.apache.derby" artifactId="derby" version="${derby.version}" />
		<getDependency libDir="lib_db" url="https://repo1.maven.org/maven2" groupId="org.apache.derby" artifactId="derbyshared" version="${derby.version}" />
		<getDependency libDir="lib_db" url="https://repo1.maven.org/maven2" groupId="org.apache.derby" artifactId="derbytools" version="${derby.version}" />
	</target>

	<target name="compile" depends="download_dependencies, download_dbconnectors">
		<path id="build.classpath">
			<fileset dir="lib">
				<include name="*.jar" />
			</fileset>
		</path>

		<javac release="17" debug="true" nowarn="true" deprecation="false" destdir="${buildPath}/bin" fork="yes" srcdir="src/main/java" includeantruntime="false" encoding="UTF-8" classpath="lib/*">			
			<classpath refid="build.classpath" />
			<compilerarg value="-Xlint:unchecked" />
			<compilerarg value="-parameters" />
		</javac>

		<copy todir="${buildPath}/bin">
			<fileset dir="src/main/resources">
				<include name="**/LanguageProperties*.properties" />
				<include name="**/*.txt" />
			</fileset>
		</copy>
	</target>

	<target name="create_versionfile">
		<basename property="CaPublicKeyFileName" file="${CaPublicKey}"/>
		<basename property="CaPublicKeyFileNameOld" file="${CaPublicKeyOld}"/>

		<delete file="${buildPath}/bin/version.txt" />
		<echo file="${buildPath}/bin/version.txt" append="false">${build.version}${line.separator}${buildTime}${line.separator}${VersionsUrl}${line.separator}${CaPublicKeyFileName}, ${CaPublicKeyFileNameOld}${line.separator}</echo>
		<delete file="src/main/resources/version.txt" />
		<echo file="src/main/resources/version.txt" append="false">${build.version}${line.separator}${buildTime}${line.separator}${VersionsUrl}${line.separator}${CaPublicKeyFileName}, ${CaPublicKeyFileNameOld}${line.separator}</echo>
	</target>

	<target name="create_jar" depends="compile, create_versionfile">
		<jar destfile="${buildPath}/DbExport-${build.version}.jar">
			<manifest>
				<attribute name="Main-Class" value="de.soderer.DbExport" />
				<attribute name="Class-Path" value="." />
				<attribute name="Rsrc-Main-Class" value="de.soderer.dbexport.DbExport" />
			</manifest>

			<fileset dir="${buildPath}/bin" />

			<zipfileset file="${CaPublicKey}" />
			<zipfileset file="${CaPublicKeyOld}" />
			<zipfileset dir="lib" includes="*.jar" excludes="*sources.jar" />
			<zipfileset dir="lib_db" includes="*.jar" />
			<zipfileset dir="src/main/resources" includes="DbExport_Icon.png" />
			<zipfileset dir="src/main/resources" includes="DbExport.ico" />
		</jar>
			
		<jar destfile="${buildPath}/DbExport.jar">
			<manifest>
				<attribute name="Main-Class" value="de.soderer.DbExport" />
				<attribute name="Class-Path" value="." />
				<attribute name="Rsrc-Main-Class" value="de.soderer.dbexport.DbExport" />
			</manifest>

			<fileset dir="${buildPath}/bin" />

			<zipfileset file="${CaPublicKey}" />
			<zipfileset file="${CaPublicKeyOld}" />
			<zipfileset dir="lib" includes="*.jar" excludes="*sources.jar" />
			<zipfileset dir="lib_db" includes="*.jar" />
			<zipfileset dir="src/main/resources" includes="DbExport_Icon.png" />
			<zipfileset dir="src/main/resources" includes="DbExport.ico" />
		</jar>
	</target>

	<available file="${user.home}/git/codeSigning.properties" property="signingPropertiesAvailable" />
	<target name="sign_jar" depends="create_jar" if="signingPropertiesAvailable">
		<signjar destDir="${buildPath}" alias="${CodeSigningKeyAlias}" keystore="${CodeSigningKeyStore}" storepass="${CodeSigningKeyStorePassword}" keypass="${CodeSigningKeyPassword}" preservelastmodified="true" tsaurl="${TsaUrl}">
			<path>
				<fileset dir="${buildPath}" includes="DbExport.jar" />
			</path>
		</signjar>
		<signjar destDir="${buildPath}" alias="${CodeSigningKeyAlias}" keystore="${CodeSigningKeyStore}" storepass="${CodeSigningKeyStorePassword}" keypass="${CodeSigningKeyPassword}" preservelastmodified="true" tsaurl="${TsaUrl}">
			<path>
				<fileset dir="${buildPath}" includes="DbExport-${build.version}.jar" />
			</path>
		</signjar>
	</target>

	<target name="cleanup_after">
		<delete dir="${buildPath}/bin" />
	</target>
</project>
